config/routes.rb
Rails.application.routes.draw do
  get 'games/games'
  devise_for :users
  root 'home#home'
  root controller: :rooms, action: :index
  get 'contact', to: 'home#contact'
  get 'games', to: 'games#games'
  get 'about', to: 'home#about'
  resources :room_messages
  resources :rooms
  post 'request_contact', to: 'home#request_contact'
  mount SimpleDiscussion::Engine => "/forum"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :room_messages, dependent: :destroy,
                           inverse_of: :room
end

app/models/room_message.rb
class RoomMessage < ApplicationRecord
  belongs_to :room, inverse_of: :room_messages

  belongs_to :user

  def as_json(options)
    super(options).merge(user_username: user.username)
  end



end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  include SimpleDiscussion::ForumUser

  validates :username, uniqueness: true, presence: true

  has_many :room_messages,
           dependent: :destroy

  def gravatar_url
    gravatar_id = Digest::MD5::hexdigest(email).downcase
    "https://gravatar.com/avatar/#{gravatar_id}.png"
  end

  def name
    "#{self.username}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email, :username])
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  def games
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def home
  end

  def contact
  end

  def request_contact
    flash[:notice] = I18n.t('home.request_contact.email_sent')
    redirect_to root_path
end

  def about
  end


end

app/controllers/room_messages_controller.rb
class RoomMessagesController < ApplicationController
  before_action :load_entities

  def create
    @room_message = RoomMessage.create user: current_user,
                                       room: @room,
                                       message: params.dig(:room_message, :message)
    
   RoomChannel.broadcast_to @room, @room_message
    
   head :ok
  end

  protected

  def load_entities
    @room = Room.find params.dig(:room_message, :room_id)
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  # Loads:
  # @rooms = all rooms
  # @room = current room when applicable
  before_action :load_entities

  def index
    @rooms = Room.all
  end

  def new
    @room = Room.new
  end

  def create
    @room = Room.new permitted_parameters

    if @room.save
      flash[:success] = "Room #{@room.name} was created successfully"
      redirect_to rooms_path
    else
      render :new
    end
  end

  def show
    @room_message = RoomMessage.new room: @room
    @room_messages = @room.room_messages.includes(:user)
  end

  def edit
  end

  def update
    if @room.update_attributes(permitted_parameters)
      flash[:success] = "Room #{@room.name} was updated successfully"
      redirect_to rooms_path
    else
      render :new
    end
  end

  protected

  def load_entities
    @rooms = Room.all
    @room = Room.find(params[:id]) if params[:id]
  end

  def permitted_parameters
    params.require(:room).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/room_messages_helper.rb
module RoomMessagesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/games/games.html.haml
.container
  %body
    <!--This is all the text for personal space avoiders game. -->
    %h1= t('.personalspaceInvadersTitle')
    %p= t('.personalspaceInvadersDescription')
    %p= t('.personalspaceInvadersExplanation')
    %p= t('.personalspaceInvadersLeaderBoard')
    %p= t('.personalspaceInvadersWindows')
    = link_to "Here","/PersonalSpaceInvaders(windows).zip"
    %p= t('.personalspaceInvadersMac')
    = link_to "Here","/PersonalSpaceInvaders(mac).zip"
    .container-fluid
      %title= t('.page_title')
      %h2= t('.game_title')
      %p= t('.game_desc')
      %p= t('.game_desc2')
      %h4 Click play to start!
      %h4="Possible answers:"
      %p="mask, sanitiser, yes, 2m, boris, december2019"


      .form
        %label{:for => "guessField"}
          ="Guess:"
        %input#guessField.guessField{:type => "text"}/
        %input#submitguess.guessSubmit{:type => "submit", :value => "Submit guess"}/
        <button onClick="window.location.reload();">Play</button>
      %body{:onload => "test()"}



      %footer
      %p.pull-right
        %a{:href => "#"} Back to top
      %p
        \© 2020 Pan Pal Inc. ·

app/views/home/contact.html.haml
.container
  %title= t('.page_title')
  %body{:onload => "function()"}
    %h1= t('.title')
    %p= t('.welcome')

  = form_tag request_contact_path,:id => 'ContactForm', method: 'post' do
    = label_tag :name, t('.name')
    = text_field_tag :name
    = label_tag :email, t('.email')
    = email_field_tag :email
    = label_tag :telephone, t('.telephone')
    = telephone_field_tag :telephone
    = label_tag :message, t('.message')
    = text_field_tag :message,'', size: 70
    = submit_tag t('.submit')

  %footer
    %p.pull-right
      %a{:href => "#"} Back to top
    %p
      \© 2020 Pan Pal Inc. ·

app/views/home/home.html.haml
.jumbotron
  .container
    %h1 Pan Pal!
    %p The one stop shop for Pandemic fun! - Welcome to our website, here you can keep up to date with the latest Covid statistics! Play covid related games and join our community. See what others are doing to keep themselves busy over lockdown!
    %p
      %a.btn.btn-primary.btn-lg{href: "about", role: "button"} Learn more »
.container
  / Example row of columns
  .row
    .col-md-4
      %h2 M Media Covid Global Info
      %p Fetched from M Media's API
      :javascript
        const endpointUK = {
            url: 'https://api.coronavirus.data.gov.uk/v1/data?',
        };

        const
            AreaType = "nation",
            AreaName = "england";


        const
            filters = [
                `areaType=${AreaType}`,
                `areaName=${AreaName}`

            ],
            structure = {
                date: "date",
                newCasesByPublishDate: "newCasesByPublishDate",
                cumCasesByPublishDate: "cumCasesByPublishDate",
                newDeaths28DaysByPublishDate: "newDeaths28DaysByPublishDate",
                cumDeaths28DaysByPublishDate: "cumDeaths28DaysByPublishDate"
            };

        const
            apiParams = `filters=${filters.join(";")}&structure=${JSON.stringify(structure)}`,
            encodedParams = encodeURI(apiParams);

        const govUkURL = `${endpointUK.url}${encodedParams}`

        fetch(govUkURL)
            .then((data) => data.json())
            .then((covidData) => generateHTMLUK(covidData))

        const generateHTMLUK = (data) => {
            console.log(data)

            const html = `
                            <div class = "dataDate" > Date: ${data.data[0].date}</div >
                            <div class = "dataCases"> Daily Cases: ${data.data[0].newCasesByPublishDate}</div>
                            <div class = "dataCasesTotal"> Total UK cases: ${data.data[0].cumCasesByPublishDate}</div>
                            <div class = "dataCasesTotal"> Daily Covid Death: ${data.data[0].newDeaths28DaysByPublishDate}</div>
                            <div class = "dataCasesTotal"> Total UK Deaths: ${data.data[0].cumDeaths28DaysByPublishDate}</div>

                        `

            const covidDataDiv = document.querySelector('.GovUKcovidData')
            covidDataDiv.innerHTML = html

        }
        const endpoint = {
            url: 'https://covid-api.mmediagroup.fr/v1/cases?country=Global',
        };


        const MMediaURL = `${endpoint.url}`
        console.log(MMediaURL)

        fetch(MMediaURL)
            .then((data) => data.json())
            .then((covidData) => generateHTML(covidData))

        const generateHTML = (data) => {
            console.log(data)

            const html = `
                            <div class = "population" > Global Population: ${data.All.population}</div >
                            <div class = "globalCases"> Total Global Cases: ${data.All.confirmed}</div>
                            <div class = "globalRecovered"> Total Global Recovered Cases: ${data.All.recovered}</div>
                            <div class = "globalDeaths"> Total Global Deaths: ${data.All.deaths}</div>
                        `

            const covidDataDiv = document.querySelector('.MMediacovidData')
            covidDataDiv.innerHTML = html

        }
      .MMediacovidData
      %a.btn.btn-default{href: "https://mmediagroup.fr/covid-19", role: "button"} View details »
    .col-md-4
      %h2 UK Gov Covid Information
      %p information from GovUk API covid database
      .GovUKcovidData
      %a.btn.btn-default{href: "https://coronavirus.data.gov.uk/", role: "button"} View details »
.container
  %footer
    %p.pull-right
      %a{:href => "#"} Back to top
      %p
      \© 2020 Pan Pal Inc. ·
/ /container
/
  Bootstrap core JavaScript
  \==================================================
/ Placed at the end of the document so the pages load faster
%script{crossorigin: "anonymous", integrity: "sha384-nvAa0+6Qg9clwYCGGPpDQLVpLNn0fRaROjHqs13t4Ggj3Ez50XnGQqc/r8MhnRDZ", src: "https://code.jquery.com/jquery-1.12.4.min.js"}
:javascript
  window.jQuery || document.write('<script src="../../assets/js/vendor/jquery.min.js"><\/script>')
%script{src: "../../dist/js/bootstrap.min.js"}
/ IE10 viewport hack for Surface/desktop Windows 8 bug
%script{src: "../../assets/js/ie10-viewport-bug-workaround.js"}

app/views/layouts/application.html.haml
%html
  %head
    %meta{'charset' => 'utf-8'}
    %meta{'http-equiv' => 'x-ua-compatible', 'content' => 'ie=edge'}



    %meta{'name' => 'description', 'content' => t('app_description')}
    %meta{'name' => 'viewport', 'content' => 'width=device-width, initial-scale=1'}

    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = javascript_include_tag 'modernizr'
    = csrf_meta_tags
    !!!
%html{lang: "en"}
  %head
    %meta{content: "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{charset: "utf-8"}/
    %meta{content: "IE=edge", "http-equiv" => "X-UA-Compatible"}/
    %meta{content: "width=device-width, initial-scale=1", name: "viewport"}/
    / The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags
    %meta{content: "", name: "description"}/
    %meta{content: "", name: "author"}/
    %link{href: "../../favicon.ico", rel: "icon"}/
    %link{href: "../../dist/css/bootstrap.min.css", rel: "stylesheet"}/
    %link{href: "../../assets/css/ie10-viewport-bug-workaround.css", rel: "stylesheet"}/
    / Custom styles for this template
    %link{href: "jumbotron.css", rel: "stylesheet"}/
    / Just for debugging purposes. Don't actually copy these 2 lines!
    /[if lt IE 9] <script src="../../assets/js/ie8-responsive-file-warning.js"></script>
    %script{src: "../../assets/js/ie-emulation-modes-warning.js"}
    / HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries
    /[if lt IE 9]
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  %body
    %nav.navbar.navbar-inverse.navbar-fixed-top
      .container
        .navbar-header
          %button.navbar-toggle.collapsed{"aria-controls" => "navbar", "aria-expanded" => "false", "data-target" => "#navbar", "data-toggle" => "collapse", type: "button"}
            %span.sr-only Toggle navigation
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          %a.navbar-brand{href: "/"} Home
          %a.navbar-brand{href: "/games"} Games
          %a.navbar-brand{href: "/forum"} Forum
          %a.navbar-brand{href: "/rooms"} Chat room
          %a.navbar-brand{href: "/contact"} Contact
          %a.navbar-brand{href: "/about"} About
        #navbar.navbar-collapse.collapse
          %form.navbar-form.navbar-right
            = render 'shared/header'
        / /.navbar-collapse

  %body

    - flash.each do |key, value|
      = content_tag :div, content_tag(:p, value), id: "#{key}" unless value.blank?


    = yield

app/views/rooms/_form.html.erb
<%= simple_form_for @room do |form| %>
  <%= form.input :name %>
  <%= form.submit "Save", class: 'btn btn-success' %>
<% end %>

app/views/rooms/_rooms.html.erb
<h3 class="text-muted mb-0">
  Rooms
</h3>

<hr class="mt-1">

<% if @rooms.present? %>
  <nav class="nav-flex-column">
    <% @rooms.each do |room| %>
      <%= link_to room.name, room_path(room), class: 'nav-link room-nav-link' %>
    <% end %>
  </nav>
<% else %>
  <div class="text-muted">
    The are no rooms
  </div>
<% end %>

<div class="mt-3">
  <%= link_to new_room_path, class: 'btn btn-primary' do %>
    Create a room
  <% end %>
</div>

app/views/rooms/edit.html.erb
<h1>
  Editing room <%= @room.name %>
</h1>

<%= render partial: 'form' %>

app/views/rooms/index.html.erb
<div class="row">
  <div class="col-12 col-md-3">
    <%= render partial: 'rooms' %>
  </div>

  <div class="col">
    <div >
      <h4 >
        Welcome to the Chat!
      </h4>

      <hr />

      <p>
        You can create or join a room from the sidebar.
      </p>
    </div>
  </div>
</div>

app/views/rooms/new.html.erb
<h1>
  Creating a room
</h1>

<%= render partial: 'form' %>

app/views/rooms/show.html.erb
<html>
  <h1 class="RName">
    <%= @room.name %>
  </h1>

  <div class="row">
    <div class="col-12 col-md-3">
      <%= render partial: 'rooms' %>
    </div>

    <div class="col">
      <div class="chat" data-channel-subscribe="room" data-room-id="<%= @room.id %>">
        <% @room_messages.each do |room_message| %>
          <div class="chat-message-container">
            <div>


              <div class="col">
                <div class="message-content">
                  <div class="text-left">
                    <strong>
                      <kbd class="ShowUsername">
                        <%= room_message.user.username %>
                      </kbd>
                    </strong>
                  </div>
                  <p class="mb-1">
                    <%= room_message.message %>
                  </p>
                  <div class="text-right">
                    <small>
                      <%= room_message.created_at %>
                    </small>
                  </div>
                </div>
              </div>
            </div>
          </div>
        <% end %>
      </div>

      <%= simple_form_for @room_message, remote: true do |form| %>
        <div class="input-group mb-3">
          <%= form.input :message, as: :string,
                                   wrapper: false,
                                   label: false,
                                   input_html: {
                                     class: 'chat-input',
                                     autocomplete: 'off'
                                   } %>
          <div class="input-group-append">
            <%= form.submit "Send", class: 'btn btn-primary chat-input' %>
          </div>
        </div>

        <%= form.input :room_id, as: :hidden %>
      <% end %>
    </div>
  </div>

  <div hidden class="d-none" data-role="message-template">
    <div class="chat-message-container">
      <div >


        <div class="col">
          <div class="message-content">
            <div class="text-left">
              <strong>
                <kbd class="ShowUsername" data-role="user-username">
                </kbd>
              </strong>
            </div>
            <p class="mb-1" data-role="message-text">

            </p>

            <div class="text-right">
              <small data-role="message-date">
              </small>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</html>

app/views/shared/_header.html.haml
.text_change
  %body
    - if user_signed_in?
      = "#{current_user.email} |"
      = link_to t('profile'), edit_user_registration_path
      = '|'
      = link_to t('logout'), destroy_user_session_path, method: 'delete'
      %br/
      = "Account Number:"
      =current_user.id
    - else
      = link_to t('login'), new_user_session_path
      = '|'
      = link_to t('sign_up'), new_user_registration_path
  -flash.each do |key, value|
    = content_tag :div, content_tag(:p, value), id: "#{key}" unless value.blank?